version: '3.8'
services:
  app:
    image: front-prod
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    depends_on:
      - backend
    
  debug-helper:
    image: busybox
    command: sh -c "sleep 10000"
    
  backend:
    image: back-prod
    build:
      context: ./todo-backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: back-prod # This will name the container hello-front-dev
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
   
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-prod
    depends_on:
      - app 
      - backend

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db

  redis: 
    image: redis
    ports: 
       - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
         - ./redis_data/:/data
volumes:
  redis_data:
  mongo_data:
  